<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_User ID_userId</name>
   <tag></tag>
   <elementGuidId>724ed3a8-d44b-4c9b-b083-8124aaaa0e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#userId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='userId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c6174e66-c227-482f-aec9-80cfa2193b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg: PD1234</value>
      <webElementGuid>5f105360-348f-4dbe-81b1-96f0d6cc46b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0b3c9c5b-1d4a-4ac3-a757-d2f22ec4fd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>userId</value>
      <webElementGuid>475922e5-7b9e-49e9-b7e3-fb03d1bcbb60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f7f386af-8427-4563-aa63-6c6f6ced31c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1v9eliy</value>
      <webElementGuid>c161bf81-8f61-4b5f-b987-b11f4793d3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd85fa9d-edf9-4f23-8128-797c4ba44839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userId&quot;)</value>
      <webElementGuid>c7c1e923-a526-43aa-bb9d-52cbb2546ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userId']</value>
      <webElementGuid>98aa75ef-5f65-44ec-b88c-13f0c924a6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section[2]/div/form/div[2]/div/div[2]/div/div/span/input</value>
      <webElementGuid>d01ac9ae-8ed6-4359-b592-260c9a79fc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/span/input</value>
      <webElementGuid>062cae8e-9da6-4dd7-8f2b-e446acc41a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Eg: PD1234' and @id = 'userId' and @type = 'text']</value>
      <webElementGuid>82190f6b-f410-4ecd-addc-33cd694ca7f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
