<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Client Account ID_clientId</name>
   <tag></tag>
   <elementGuidId>c88202a1-4b26-4dd6-8938-d432c9a393a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clientId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clientId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8af2722a-acbb-4549-94bb-619d8ac4dc48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Eg: PD1234</value>
      <webElementGuid>e44e8d09-f152-491a-919e-bd1e3009dd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d7effe8f-3f68-4559-ab00-ab2633a4e1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clientId</value>
      <webElementGuid>9025c4b2-3363-4161-a670-d896d6311e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb201c2f-36a8-4f5f-a83b-c25455e27acf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input css-1v9eliy</value>
      <webElementGuid>ee051b1b-d638-45f4-bd4e-47c677a5a9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9d30593b-533e-4fa6-979c-4f8a7e2eca0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clientId&quot;)</value>
      <webElementGuid>70347a82-1159-43cc-89fa-2e796916643c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clientId']</value>
      <webElementGuid>6507b4c4-9f03-45ab-8a2e-c9acda242482</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section[2]/div/form/div/div/div[2]/div/div/span/input</value>
      <webElementGuid>283b8c64-3629-402f-bb01-1edb6fc36e0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>51e81c5f-bc96-40a5-bd54-2a982e2a2e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Eg: PD1234' and @id = 'clientId' and @type = 'text']</value>
      <webElementGuid>f62a854e-d007-4168-b371-fcab64077230</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
